# stellar.toml
VERSION="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
SIGNING_KEY="GCX7CCSPWP7533ZLXHIAIDGGGHX42IWHS63OJ46Y5YLDP6NGPESUWWYR"
HORIZON_URL="https://horizon.domain.com"
ACCOUNTS=[
"GCX7CCSPWP7533ZLXHIAIDGGGHX42IWHS63OJ46Y5YLDP6NGPESUWWYR"
]

[DOCUMENTATION]
ORG_NAME="name of your organization"
ORG_URL="https://lovetokenstellar.github.io"
ORG_LOGO="https://lovetokenstellar.github.io/LoveToken.png"
ORG_DESCRIPTION="This is a token for spreading love around the world"
ORG_PHYSICAL_ADDRESS="Antarctica"
ORG_OFFICIAL_EMAIL="n/a"

[[CURRENCIES]]
code="LOVETOKEN"
issuer="GCX7CCSPWP7533ZLXHIAIDGGGHX42IWHS63OJ46Y5YLDP6NGPESUWWYR"
display_decimals=2
name="LOVETOKEN"
desc="1 Love token can be redeemed for 1 hug"
image="https://lovetokenstellar.github.io/LoveToken.png"

